/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Entry = IDL.Record({
  'id' : IDL.Nat,
  'survivalTime' : IDL.Nat,
  'placement' : IDL.Nat,
  'timestamp' : Time,
  'playerName' : IDL.Text,
  'kills' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllEntries' : IDL.Func([], [IDL.Vec(Entry)], ['query']),
  'getTopKills' : IDL.Func([], [IDL.Vec(Entry)], ['query']),
  'getTopPlacements' : IDL.Func([], [IDL.Vec(Entry)], ['query']),
  'submitMatch' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Entry = IDL.Record({
    'id' : IDL.Nat,
    'survivalTime' : IDL.Nat,
    'placement' : IDL.Nat,
    'timestamp' : Time,
    'playerName' : IDL.Text,
    'kills' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllEntries' : IDL.Func([], [IDL.Vec(Entry)], ['query']),
    'getTopKills' : IDL.Func([], [IDL.Vec(Entry)], ['query']),
    'getTopPlacements' : IDL.Func([], [IDL.Vec(Entry)], ['query']),
    'submitMatch' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };